spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/sell?characterEncoding=utf-8
  jpa:
    show-sql: true
server:
  context-path: /sell
logging:
  pattern:
    console: "%d - %msg%n"
  path: /var/log/tomcat/